# Generated by Django 5.0.6 on 2024-05-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_note_order_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='notes',
            new_name='order_note',
        ),
    ]
